# Generated by Django 4.2.5 on 2023-09-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lname',
            new_name='last_name',
        ),
    ]
